CREATE SEQUENCE SEQ_MOBILIDADES
    START WITH 1
    INCREMENT BY 1 NOCACHE
  NOCYCLE;

CREATE TABLE tb_mobilidade (
                               mobilidade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               partida VARCHAR2(255) NOT NULL,
                               destino VARCHAR2(255) NOT NULL,
                               status VARCHAR2(50) NOT NULL,
                               release_date DATE
);


